//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Dueño { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public int Telefono { get; set; }
        public string Direccion { get; set; }
        public string Rep_Datos { get; set; }
        public string Incorp_Fiscal { get; set; }
    
        public virtual ICollection<Nota> Nota { get; set; }
    }
}
