//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int id { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaRecibido { get; set; }
        public int idEmpresa { get; set; }
        public int Folio { get; set; }
        public int idNotaPrenda { get; set; }
        public int idClientes { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual NotaPrenda NotaPrenda { get; set; }
    }
}
