//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaPrenda
    {
        public NotaPrenda()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int id { get; set; }
        public int idNota { get; set; }
        public int idPrenda { get; set; }
        public int idPrecio { get; set; }
    
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Precio Precio { get; set; }
        public virtual Prenda Prenda { get; set; }
    }
}
