//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenda
    {
        public Prenda()
        {
            this.NotaPrenda = new HashSet<NotaPrenda>();
        }
    
        public int id { get; set; }
        public int idTipoPrenda { get; set; }
        public int idTipoArreglo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<NotaPrenda> NotaPrenda { get; set; }
        public virtual TipoArreglo TipoArreglo { get; set; }
        public virtual TipoPrenda TipoPrenda { get; set; }
    }
}
