//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArreglo
    {
        public TipoArreglo()
        {
            this.Precio = new HashSet<Precio>();
            this.Prenda = new HashSet<Prenda>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public int idPrecio { get; set; }
    
        public virtual ICollection<Precio> Precio { get; set; }
        public virtual ICollection<Prenda> Prenda { get; set; }
    }
}
